Internals: Run format-make

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -186,7 +186,7 @@ test-snap test-diff:
 
 examples: all_nomsg
 	for p in $(EXAMPLES) ; do \
-	  $(MAKE) -C $$p VERILATOR_ROOT=`pwd` || exit 10; \
+		$(MAKE) -C $$p VERILATOR_ROOT=`pwd` || exit 10; \
 	done
 
 ######################################################################
@@ -276,7 +276,7 @@ mkbindirs:
 installbin: | mkbindirs
 	cd $(srcdir)/bin; \
 	for p in $(VL_INST_PUBLIC_SCRIPT_FILES) ; do \
-	  $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$p; \
+		$(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$p; \
 	done
 	perl -p -i -e 'use File::Spec;' \
 	           -e' $$path = File::Spec->abs2rel("$(realpath $(DESTDIR)$(pkgdatadir))", "$(realpath $(DESTDIR)$(bindir))");' \
@@ -284,11 +284,11 @@ installbin: | mkbindirs
 	           -- "$(DESTDIR)/$(bindir)/verilator"
 	cd bin; \
 	for p in $(VL_INST_PUBLIC_BIN_FILES) ; do \
-	  $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$p; \
+		$(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$p; \
 	done
 	cd $(srcdir)/bin; \
 	for p in $(VL_INST_PRIVATE_SCRIPT_FILES) ; do \
-	  $(INSTALL_PROGRAM) $$p $(DESTDIR)$(pkgdatadir)/bin/$$p; \
+		$(INSTALL_PROGRAM) $$p $(DESTDIR)$(pkgdatadir)/bin/$$p; \
 	done
 
 installredirect: installbin | mkbindirs
@@ -298,7 +298,7 @@ installredirect: installbin | mkbindirs
 	           -e 's/RELPATH.*/"$$path";/g' -- "${srcdir}/bin/redirect.tmp"
 	cd $(srcdir)/bin; \
 	for p in $(VL_INST_PUBLIC_SCRIPT_FILES) $(VL_INST_PUBLIC_BIN_FILES) ; do \
-	  $(INSTALL_PROGRAM) redirect.tmp $(DESTDIR)$(pkgdatadir)/bin/$$p; \
+		$(INSTALL_PROGRAM) redirect.tmp $(DESTDIR)$(pkgdatadir)/bin/$$p; \
 	done
 	rm ${srcdir}/bin/redirect.tmp
 
@@ -307,14 +307,14 @@ installredirect: installbin | mkbindirs
 installman: $(VL_INST_MAN_FILES)
 	$(MKINSTALLDIRS) $(DESTDIR)$(mandir)/man1
 	for p in $^ ; do \
-	  $(INSTALL_DATA) $$p $(DESTDIR)$(mandir)/man1/$$p; \
+		$(INSTALL_DATA) $$p $(DESTDIR)$(mandir)/man1/$$p; \
 	done
 
 installdata:
 	$(MKINSTALLDIRS) $(DESTDIR)$(pkgdatadir)/include/gtkwave
 	$(MKINSTALLDIRS) $(DESTDIR)$(pkgdatadir)/include/vltstd
 	for p in $(VL_INST_INC_BLDDIR_FILES) ; do \
-	  $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/$$p; \
+		$(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/$$p; \
 	done
 	cd $(srcdir) \
 	; for p in $(VL_INST_INC_SRCDIR_FILES) ; do \
@@ -680,7 +680,7 @@ $(COVERAGE_DIR)/verilator.info: $(GCNO_FILES) $(GCDA_FILES)
 	@echo "####################################################################"
 	@mkdir -p $(COVERAGE_DIR)
 	/usr/bin/time -f "That took %E" \
-    $(FASTCOV) $(FASTCOV_OPT) --output $@
+	$(FASTCOV) $(FASTCOV_OPT) --output $@
 
 # Filter combined .info file for patch coverage
 $(COVERAGE_DIR)/verilator-patch.info: $(COVERAGE_DIR)/verilator.info
@@ -699,7 +699,7 @@ $(COVERAGE_DIR)/report/index.html: $(COVERAGE_DIR)/verilator$(if $(COVERAGE_REF_
 	@echo "####################################################################"
 	@rm -rf $(COVERAGE_DIR)/report
 	[ -f $(COVERAGE_DIR)/empty-patch ]] || /usr/bin/time -f "That took %E" \
-    $(GENHTML) $(GENHTML_OPT) --output-directory $(COVERAGE_DIR)/report $^ || true
+	$(GENHTML) $(GENHTML_OPT) --output-directory $(COVERAGE_DIR)/report $^ || true
 	@# Uncommitted changes not tracked, force rebuild on next run if patch coverage
 	@$(if $(COVERAGE_REF_BASE),mv $(COVERAGE_DIR)/verilator-patch.info $(COVERAGE_DIR)/verilator-patch-last.info)
 
@@ -712,20 +712,20 @@ coverage-combine: $(COVERAGE_DIR)/verilator.info
 coverage-report:
 	@$(MAKE) --no-print-directory $(COVERAGE_DIR)/report/index.html || true
 	@if [ -f $(COVERAGE_DIR)/report/index.html ]; then \
-    echo "####################################################################"; \
-    echo "# Coverage report is at: $(COVERAGE_DIR)/report/index.html"; \
-    echo "# Use 'make coverage-view' to open it in your default browser"; \
-    echo "####################################################################"; \
-  elif [ -f $(COVERAGE_DIR)/empty-patch ]; then\
-    echo "####################################################################"; \
-    echo "# Patch is empty"; \
-    echo "####################################################################"; \
-  else \
-    echo "####################################################################"; \
-    echo "# Failed to create coverage report. Maybe no data, or error?"; \
-    echo "####################################################################"; \
-    false; \
-  fi
+		echo "####################################################################"; \
+		echo "# Coverage report is at: $(COVERAGE_DIR)/report/index.html"; \
+		echo "# Use 'make coverage-view' to open it in your default browser"; \
+		echo "####################################################################"; \
+	elif [ -f $(COVERAGE_DIR)/empty-patch ]; then \
+		echo "####################################################################"; \
+		echo "# Patch is empty"; \
+		echo "####################################################################"; \
+	else \
+		echo "####################################################################"; \
+		echo "# Failed to create coverage report. Maybe no data, or error?"; \
+		echo "####################################################################"; \
+		false; \
+	fi
 
 # Open covarage report in default web browser
 .PHONY: coverage-view
@@ -749,8 +749,8 @@ maintainer-clean::
 
 clean mostlyclean distclean maintainer-clean maintainer-copy::
 	for dir in $(SUBDIRS); do \
-	  echo making $@ in $$dir ; \
-	  $(MAKE) -C $$dir $@ ; \
+		echo making $@ in $$dir ; \
+		$(MAKE) -C $$dir $@ ; \
 	done
 
 clean mostlyclean distclean maintainer-clean::
